- .editorconfig
- examples/concept_insights.v1.js
- services/concept_insights/v1.js
- test/test.concept_insights.v1.js
This should fix #10 and also be a good pattern to follow for other APIs that expect JSON blobs in the HTTP request.
> ConceptInsights.semanticSearch ids as an array of strings instead of a JSON blob

- lib/index.js
- services/authorization/v1.js
- test/test.authorization.v1.js
This is a PR for the new authorization service.  The Authorization service is structures like the other services, but only has a single function that sits on its prototype: getToken
This function takes a options object with a required 'url' property, since sending the URL of the intended resource for the Authorization service is required (tokens carry permissions that are constrained by path).
The other possibility is instead of passing in the URL, we could pass in the service that the token will be used with, which "knows" what the URL is.  Would this be a better approach?
I'm open to suggestions on improvements, and will check back by in a few hours (I need to spend a block of time now finishing up additional TTS demo app features).
> Add authorization service wrapper

- examples/personality_insights.v2.js
- services/personality_insights/v2.js
- test/test.personality_insights.v2.js
Now Personality Insights service wrapper supports the parameter 'acceptLanguage' which indicates to the service the language expected for the output. Also added some documentation for this service.
> Added 'acceptLanguage' parameter for PI wrapper.

- examples/search_lifecycle.v1.js
- services/search/v1.js
- test/test.search.v1.js
Also fixes a bug in the search_lifecycle example with missing var.
> Use passed in url when creating Solr client

- README.md
The callback for the authorization api getToken function takes the arguments (err, token), not just (token).  It's possible that the documentation should be changed further to reflect that so that the callback looks like
function (err, token) {
if (err) {
console.log('error:  ' + err);
} else {
//use token here
}
}
> fixed the documentation for the  authorization api

- services/concept_insights/v2.js
Concept insights v2.js was missing a return statement after all callbacks on error that were handled separately from the request helper.
> concept_insights/v2.js: adding return statements after callback(err).

- services/tone_analyzer/v2.js
- test/test.tone_analyzer.v2.js
Adds a new V2 api wrapper for Tone Analyzer. The Tone Analyzer API is changing (about to be published), mainly changing /synonym from POST to GET. 
v1 wrapper is unchanged. v2 wrapper is added. test cases for v2 are also added.
> adding Tone Analyzer v2

- services/tone_analyzer/v2.js
- test/test.tone_analyzer.v2.js
Fix to initial version of v2.js module: api endpoint changed to "synonyms"
> fixed Tone Analyzer v2 synonyms API endpoint

- services/question_and_answer/v1.js
This fixes issue 112 (https://github.com/watson-developer-cloud/nodejs-wrapper/issues/112), which addresses the fact that you could previously not add the formattedAnswer parameter to the Q&A invocation.
> Added formattedAnswer parameter to question body options

- services/retrieve_and_rank/v1.js
- test/test.retrieve_and_rank.v1.js
@gjs29 Can you verify if `deleteCollection`, `createCollection` and `listCollections` are actually `GET` calls and not `POST` as described in:
* [swagger](http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/apis/#!/retrieve-and-rank/adminAction)
* [API Reference](http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/retrieve-and-rank/api/v1/#delete_solr_collection).
I'm looking at the [Solr documentation](https://cwiki.apache.org/confluence/display/solr/Collections+API) and looks like those are `GET` requests but I want to make sure.
> update retrieve and rank

- examples/document_conversion_integration.v1-experimental.js
By adding this configuration example we want to show developers
the way they can set attributes to tune the document conversion.
> Adds configuration example for the html-to-html conversion step

- README.md
- package.json
- services/document_conversion/v1-experimental.js
- test/test.document_conversion.v1-experimental.js
The Document Conversion Service will soon require a "version" query
parameter on all requests. In the future, this will be used to avoid
breaking changes to behavior when the service is upgraded to newer
versions.
> [DCS] Adds Version Date param

- package.json
- services/tradeoff_analytics/v1.js
- test/test.tradeoff_analytics.v1.js
Added support to the generate_visualization query param
> [tradeoff-analytics] Add support for "generate_visualization"

- lib/alchemy_endpoints.json
getFormat in helper.js should not immediately associate the "url" parameter with an Alchemy URL API call. Alchemy HTML and Text APIs can also pass "url" parameters.
[helper.js](https://github.com/watson-developer-cloud/node-sdk/blob/master/lib/helper.js)
``` javascript 
/**
* Returns the first match from formats that is key the params map
* otherwise null
* @param  {Object}  params   The parameters
* @param  {Array}  requires The keys we want to check
*/
getFormat: function(params, formats) {
if (!formats || !params)
return null;
for(var i = 0; i < formats.length; i++) {
if (formats[i] in params)
return formats[i];
}
return null;
}
```
[alchemy_language/v1.js](https://github.com/watson-developer-cloud/node-sdk/blob/master/services/alchemy_language/v1.js)
``` javascript
var endpoints …
```
> Move "url" attributes to fix endpoint selection

- README.md
Example on the readme.md page for language translation gives an error. Issue #240
The language translation function call had an extra parameter, which was causing problems in using the functionality.
In the example on the main page, the *model-id* field is causing problems:
```
language_translation.translate({
text: 'A sentence must have a verb', source : 'en', target: 'es', model_id: '<model-id>' },
function (err, translation) {
if (err)
console.log('error:', err);
else
console.log(JSON.stringify(translation, null, 2));
});
```
> Updated language translation example

- services/speech_to_text/v1.js
Adds the `profanity_filter` to allowed `PARAMS_ALLOWED` array for Speech To Text
Fixes #243
> add 'profanity_filter' to PARAMS_ALLOWED for Speech To Text

- services/alchemy_language/v1.js
AlchemyLanguage expects `model` to be a query parameter in entities and typed relations calls.
> AlchemyLanguage wants "model" as query param

- services/visual_recognition/v3.js
Error found in the visual-recognition-demo
```none
App/1 at Request._callback (/home/vcap/app/node_modules/watson-developer-cloud/lib/requestwrapper.js:68:5)
App/1/home/vcap/app/node_modules/watson-developer-cloud/services/visual_recognition/v3.js:77
App/1TypeError: cb is not a function
App/1 at Request.self.callback (/home/vcap/app/node_modules/request/request.js:200:22)
App/1 cb(err, result);
App/1 at Request.emit (events.js:172:7)
App/1 at emitTwo (events.js:87:13)
App/1 at emitOne (events.js:82:20)
App/1 at /home/vcap/app/node_modules/watson-developer-cloud/services/visual_recognition/v3.js:77:9
App/1 at Request.emit (events.js:169:7)
App/1 at Request.<anonymous> (/home/vcap/app/node_modules/request/request.js:1067:10)
App/1 at IncomingMessage.<anonymous> …
```
>  Fix visual recognition bug when calling the method without a callback

- services/tone_analyzer/v3.js
- test/test.tone_analyzer.v3.js
Allows instantiating a Tone Analyzer service with customer http headers.
Current code overrides all headers. With this code (only change, uses `extend(true, ...))` one can instantiate the service for example:
```
var toneAnalyzer = watson.tone_analyzer({
url: 'https://gateway.watsonplatform.net/tone-analyzer/api/',
...
headers: { 'Accept-Language': 'es' }
})
```
and have these headers honored. This is the only way to get internationalized values through the node sdk.
> allow having http headers in Tone Analyzer wrapper options

- README.md
- services/conversation/v1-experimental.js
- services/conversation/v1.js
- test/test.integration-all-services.js
Adding Conversation v1 (GA); no changes except URL. Also added deprecation warning to v1-experimental.
> Conversation v1

- examples/document_conversion.v1.js
- services/document_conversion/v1.js
This submission includes new API call for the Document Conversion Service that will allow you to access the index_document endpoint:
DocumentConversion.prototype.index
This is a synchronous call that will allow you to convert and index a document into a SOLR collection (via the Retrieve and Rank service) in one operation.  A "dry run" of the indexing can be submitted to preview the indexed results prior to actual indexing.
> [document-conversion] Adds index document API

- lib/alchemy_endpoints.json
- services/alchemy_language/v1.js
- test/test.alchemy_language.v1.js
- Add [extract dates](http://www.ibm.com/watson/developercloud/alchemy-language/api/v1/?curl#date_extraction) to AlchemyLanguage
- Fix descriptions for publication date, combined call
> Add Date Extraction to AlchemyLanguage

- services/document_conversion/v1.js
- test/test.document_conversion.v1.js
Version date default is 2015-12-15.
Examples fail with current lower case conversion_targets
* updates from 2015-012-01 to 2015-12-15
* changes conversion target to lowercase. See
http://www.ibm.com/watson/developercloud/doc/document-conversion/updates
.shtml#previous and search for **14 March 2016**
I suspect that you'll want to change the code to support both uppercase and lowercase conversion targets. Tell me where to put that and I'll add that.
> Change current version date and set conversion target to lower case

- visual-recognition/v3.js
The retrain function was concatinating keys badly if only
one field was submitted. There was another concat problem with the
classifier_id
> Fixes issue with retraining function

- examples/browserify/README.md
- examples/conversation_tone_analyzer_integration/tone_conversation_integration.v1.js
- examples/conversation_tone_analyzer_integration/tone_detection.js
Depending on use-case, there might be a need to maintain tone history for each user utterance or not.  The earlier code version, by default always stored tone history. This update adds a flag "maintainToneHistoryInContext". Developer can set this value to false to not maintain tone history in context. 
When maintainToneHistoryInContext == true
Conversation context will have - tone for current utterance as well as tones for all prior user utterances.
When maintainToneHistoryInContext == false
Conversation context will only have - tone for current utterance
> User can choose whether to maintain tone history for each utterance 

- README.md
A very simple fix for the conversation example in the readme file, it was missing the `text` key to work properly.
> fixed an error in the Conversation service example

- document-conversion/v1.js
- test/unit/test.document_conversion.v1.js
it has been reported that setting the charset is not required
for html files, this removes the auto-setting of charset for html files
content types.
Fixes #332
> removes setting of charset on html content type

- README.md
The current Conversation overview link directs to a 404 page. 
None 
Thanks for contributing to the Watson Developer Cloud!
> Fix: Updated link to Conversation documentation.

- README.md
Update R&R url referenced in README.md, from `http://watson.stage1.mybluemix.net/watson/developercloud/retrieve-rank.html` to `https://www.ibm.com/watson/developercloud/retrieve-rank.html`.
See issue https://github.com/watson-developer-cloud/node-sdk/issues/340.
> Fix R&R's url in README.md 

- discovery/v1.js
- test/unit/test.discovery.v1.js
Adds ability to create collections and add documents
> expanded discovery calls

- discovery/v1.js
- examples/discovery.v1.js
The problem was that the filename wasn't being set
correctly in the multipart form upload and the service was rejecting
it.  This also adds an example for discovery that shows adding a document.
Fixes #369
> Fixes issue where adding a document as buffer/string fails

- lib/requestwrapper.js
- speech-to-text/v1.js
- test/unit/test.wrapper.js
- text-to-speech/v1.js
Returns a node stream and emit an error if the callback is null. Useful when using streams instead of callbacks:
```js
textToSpeech.synthesize({})
.on('error', function(error) {
console.log(error); // output: "Error: Missing required parameters: text"
})
.pipe(fs.createWriteStream('../resources/tts-output.ogg'));
```
I added a test case and also updated STT and TTS to use `requiredParams` instead of manually checking for missing parameters.
> Returns a node stream if callback is null

- conversation/v1.js
- test/integration/test.conversation.js
Added new workspace API tests based on Christophe Guittet (cguittet's pull request):
Added methods:
createWorkspace
listWorkspaces
getWorkspace
deleteWorkspace
updateWorkspace
workspaceStatus
workspaceLogs
New APIs are documented here: https://watson-api-explorer.mybluemix.net/apis/conversation-v1
> [Conversation] Update to leverage new workspace APIs with tests

- test/unit/test.tradeoff_analytics.v1.js
- tradeoff-analytics/v1.js
see #393 
Sorry, I could not run the tests. 
getting errors:
```
C:\WORK\2017Q1\wdc-node-sdk\node_modules\.bin\dependency-lint:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
^^^^^^^
SyntaxError: missing ) after argument list
at Object.exports.runInThisContext (vm.js:76:16)
at Module._compile (module.js:513:28)
at Object.Module._extensions..js (module.js:550:10)
at Module.load (module.js:458:32)
at tryModuleLoad (module.js:417:12)
at Function.Module._load (module.js:409:3)
at Module.require (module.js:468:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (C:\WORK\2017Q1\wdc-node-sdk\test\dependency-lint.js:4
:3)
at Module._compile (module.js:541:32)
```
- [X ] tests are included
- [ X] documentation is changed or added
> [Tradeoff analytics] add find_preferable_options param

- README.md
- conversation/v1.js
- examples/conversation.v1.js
- test/integration/test.conversation.js
- test/unit/test.conversation.v1.js
Version 2017-02-03 of the Conversation API has been released. This PR supports that API version change.
> Update the API version to allow support for absolute confidence scores and irrelevant input detection.

- README.md
Just changed the url to the Language Translator documentation to go directly to the index.html page.
> Edited LT doc link to go directly to index.html page

- discovery/v1.js
- test/unit/test.discovery.v1.js
Implementing update environment feature for Watson discovery service.
@nfriedly Please review  and let me know if any changes are require.
> Implementing update environment feature for WDS

- conversation/v1.js
- speech-to-text/recognize_stream.js
- test/integration/test.conversation.js
Hi,
I update the conversation API with : 
- Entities
- Values
- Synonyms
- Logs
Rémy.
> [Conversation] Update API

- examples/tone_analyzer.v3.js
- test/integration/test.tone_analyzer.js
- test/unit/test.tone_analyzer.v3.js
- tone-analyzer/v3.js
Fixes #436 **[tone-analyzer] tone_chat function parameter and API Reference need correction bug**
> :art::bug: use utterances as top level param

- tone-analyzer/v3.js
Matches comment "Utterances must be a JSON object."
> Changed tone_chat parameter `params.utterances` argument type to Object

- README.md
- discovery/v1.js
- examples/discovery.v1.js
- test/unit/test.discovery.v1.js
Adds the `sort` parameter to the Discovery `query` method -> see https://watson-api-explorer.mybluemix.net/apis/discovery-v1#!/Queries/get_v1_environments_environment_id_collections_collection_id_query for details
> [discovery] Add sort parameter for Discovery query

- discovery/v1.js
- test/resources/discovery-sampleAddConf.json
- test/resources/discovery-sampleUpdateConf.json
- test/unit/test.discovery.v1.js
Hi There,
I have implemented the create and update configuration feature  for discovery service. 
The configuration can done through a JSON file.
@
> [Discovery]--create and update of configuration using config json file.

- discovery/v1.js
- test/unit/test.discovery.v1.js
Potential contentions:
- I now pass `size: ""` straight through to the service (as truthy invalid values always have been). I didn't think it was explicitly "empty" enough to overwrite, you may disagree.
- The `createEnvironment` call sends a `multipart/related` request and I couldn't find any other unit tests examining bodies of this type, so I wrote a basic inspection function rather than bringing in multipart parsing libraries etc.
Open to suggestions - thanks for your time
> [discovery] createEnv with size 0 for Issue #461

- lib/requestwrapper.js
Turns this:
```
{
"message": "[object Object]",
"stack": "...",
"code": 500
}
```
Into this:
```
{
"message": "{\"error\":\"Dialog Service Error: A runtime error occurred\"}",
"stack": "...",
"code": 500
}
```
> Fixing error parsing

- examples/conversation_tone_analyzer_integration/tone_conversation_integration.v1.js
- tradeoff-analytics/v1.js
The test suite is currently failing with some `eslint` failures.
```bash
> eslint --print-config .eslintrc.js | eslint-config-prettier-check
No rules that are unnecessary or conflict with prettier were found.
/svt/jenkins/workspace/SVT-V6-IBM-CITGM/ARCH/s390x/GCC/gcc48/OS/ubuntu-16.04/TAG/svt/tmp/258a1c74-b82e-4cf7-a380-2fe790976803/watson-developer-cloud/examples/conversation_tone_analyzer_integration/tone_conversation_integration.v1.js
13:7   error  Unexpected tab character  no-tabs
15:10  error  Unexpected tab character  no-tabs
17:7   error  Unexpected tab character  no-tabs
18:7   error  Unexpected tab character  no-tabs
19:7   error  Unexpected tab character  no-tabs
21:7   error  Unexpected tab character  no-tabs
80:5   error  Unexpected tab character  no-tabs …
```
> linter: fixup linter failures

- README.md
- conversation/v1.js
- dialog/v1.js
Just updated the links in readme and JS files that were pointing to the Conversation doc on WDC to point to them in their new location on Bluemix Docs site.
> Updating Conversation doc links

- README.md
- Update links for Watson docs and marketing pages.
- Update UI instructions for service credentials.
- Change headings to sentence caps consistently
- Remove link definitions for unreferenced links
> Updating links to documentation

- lib/requestwrapper.js
- package-lock.json
- package.json
This removes dependency `string` since it wasn't being used for much, and there's currently no upgrade path to avoid the vulnerability.
This code is covered by many existing tests.
> remove dep "string"; closes #502

- language-translator/v2.js
Previously options.url was called even if options was null, causing error of options.url being undefined rather than options being undefined.
- [ x] `npm test` passes (tip: `npm run autofix` can correct most style issues)
> :bug: Fixed bug with calling options.url if options param was null

- conversation/v1.js
- test/integration/test.conversation.js
> [Conversation] Added dialog node methods

- discovery/v1.js
Add following parameter for passage extraction.
passages.fields: A comma-separated list of fields in the index that passages will be drawn from.
passages.count: The maximum number of passages to return. 
passages.characters: The approximate number of characters that any one passage should have.
Fixes #500
> add passage extraction parameters

- test/unit/test.getFormat.js
- test/unit/test.getMissingParams.js
- test/unit/test.isHTML.js
- test/unit/test.stripTrailingSlash.js
This pull request adds some tests for the functions in helper.js
> Added tests for helper functions

- README.md
- examples/text_to_speech.v1.js
- text-to-speech/v1.js
To resolve Issue #324, I wrote a function to intercept the stream, calculate the proper file size, edit the stream, and return it.
As I did this, I realized that it is not really possible without returning a Promise - reading/editing the stream involves an asynchronous process that finishes _after_ the function ends and the user calls `pipe()` on the returned stream (which is undefined until the asynchronous process finishes).
Glenn mentioned that we were hoping to use Promises in the next major release of the SDK and suggested that I make a PR with my change, just commented out for now, so that we have the code when we want it.
If the user expects a Promise when using this service, this function accurately repairs the WAV header.
I did look at the `wav` package after reading the comments …
> [text-to-speech] Repair WAV headers. #324

- discovery/v1-generated.ts
- language-translator/v2-generated.ts
- lib/base_service.ts
- lib/helper.ts
- lib/requestwrapper.ts
- visual-recognition/v3-generated.ts
- visual-recognition/v3.ts
> Core-SDK Improvements

- .gitignore
- package.json
Updates:
- `package.json` to provide coverage report in `HTML` for tests
- `gitignore` to ignore `.nyc_output` files
> Update test script to generate a coverage report

- personality-insights/v3-generated.ts
- test/unit/test.personality_insights.v3.js
This pull request manually modifies the generated code for personality insights. It removes the `csv_headers` query parameter from `profile`, which is hardcoded to accept only `application/json`.
1. When supported by the generator, we expect to generate multiple methods as we have handwritten here, `profile` and `profile_csv`.
2. I _did not_ remove the `csv_headers?: boolean` declaration from the `ProfileParams` type. This allows `profile` and `profile_csv` to accept the same type for `params`. It also simplifies code in the adapter and tests, which would otherwise need some further refactoring.
> Remove csv_headers query param from profile method

- discovery/v1-generated.ts
- test/unit/test.discovery.v1.js
* Addition of two new operations, namely `queryRelations()` and `queryEntities()`.
* Add unit tests for the new methods
> Regenerate Discovery with Latest Swagger

- lib/helper.ts
- test/integration/test.visual_recognition.custom_classifiers.js
- test/unit/test.visual_recognition.v3.js
- visual-recognition/v3.ts
Fixes issue around using defaults for classifier_ids and owners. Fixes issue temporarily for using Buffers with VR without providing filenames. I've opened an issue with the VR team to track the Buffer without filename issue.
> Fix Visual Recognition Adapter

- discovery/v1.ts
Fixes #591 . The adapter should not call `split` on the return parameter. The `requestwrapper` will handle array query parameters.
> Fix Discovery Adapter

- dialog/v1.ts
- index.ts
- lib/requestwrapper.ts
Some of the services only pickup the first instance of a query parameter if it's repeated multiple times in the query string, i.e. `&return=foo&return=bar`. This PR unifies the behavior so that we're always sending a comma separated value, i.e `&return=foo,bar`.
> Array Query Params

- README.md
- examples/personality_insights.v2.js
- examples/personality_insights.v3.js
- natural-language-classifier/v1-generated.ts
- scripts/jsdoc/generate_index_html.sh
- test/resources/sampleHtml.htm
- test/resources/sampleHtml.html
Updating links that point to WDC documentation to go to the Watson
console. Also updating other links that are outdated.
> Update links to developercloud

- examples/tone_analyzer.v3.js
Simply puts a longer sentence in the example, old one was too short to get any feedback from tone analyzer.
> Updated tone analyzer example with a longer phrase

- test/resources/auth.example.js
Fixes #626. It was only in one place, auth.example.js
> Removed reference to translation

- authorization/v1.ts
- conversation/v1-generated.ts
- dialog/v1.ts
- discovery/v1-generated.ts
- index.ts
- language-translator/v2-generated.ts
- lib/base_service.ts
- natural-language-classifier/v1-generated.ts
- personality-insights/v2.ts
- personality-insights/v3-generated.ts
- speech-to-text/v1-generated.ts
- text-to-speech/v1-generated.ts
- tone-analyzer/v3-generated.ts
- visual-recognition/v3-generated.ts
This PR changes the name of the internal `version` property of BaseService to `serviceVersion`.  I believe this is purely an internal change.  All tests pass.
The purpose of this change is to lay the foundation for using 'version' as the parameter name for the "version date" that is passed in to some services.
> Rename base service version property to serviceVersion

- natural-language-understanding/v1.ts
Change to NLU to rename version to serviceVersion.  This is a fix to PR #628 which did this rename for all the other services but missed NLU.
> Fix NLU missed in version to serviceVersion change

- lib/recognize-stream.ts
When writing to a RecognizeStream instance configure with a param 'content_type' instead of 'content-type' and the format can not be recognized from the first chunk (for example because we are directly streaming audion in L16 format) there is an exception generated.
Both  'content_type' and 'content-type' are supposed to be supported and the method 'initialize()' homogenize those properties but at this point in the code it is not yet called.
> Fix do not raise error when using content_type instead of "content-type" and format is unrecognized

- lib/base_service.ts
- lib/requestwrapper.ts
- test/unit/test.base_service.js
- test/unit/test.visual_recognition.v3.js
- test/unit/test.wrapper.js
- Allow the user to pass an `access_token` into the constructor
- Allow the user to reset this token with a setter method when the token expires and they get a new one
- When a token is passed in the constructor or setter method, the authentication header is automatically set
I also removed the specific error handling that prints the credentials the SDK expected. The way this is implemented would make it too complicated to evolve as we accept multiple styles of authentication. I think it is cleaner and just as informative to tell the user their credentials are wrong and point them to the documentation. Let me know what you think about that.
I also noticed that if you pass in something that would be a valid credential (like an `api_key`) to a service that doesn't support that (like …
> accept access_token

- lib/base_service.ts
- test/unit/test.base_service.js
Using `options` instead of `_options` leads to only instantiating the token manager if the intention for IAM usage was specified in the constructor and not in the environment variables or VCAP services. This PR corrects that.
> fix bug that prevented reading iam apikey from env

- examples/speech_to_text.v1.js
The current example for STT is out of date. It includes a couple deprecated events, which I removed. I also added some comments explaining the two different ways to use the stream:
1. Getting the full response back as an object
2. Getting just the transcriptions as strings
The last thing I did was change the testing console statements to be what I felt was cleaner and would allow for printing stringified objects.
> update stt example

- .github/CONTRIBUTING.md
- .releaserc
- .travis.yml
- README.md
- RELEASE.md
- commitlint.config.js
- package-lock.json
- package.json
This PR adds `semantic-release` integration to automate SDK releases. With this, the SDK will be released with successful `master` builds (assuming `semantic-release` determines there should be a release - see [here](https://github.com/semantic-release/commit-analyzer#release-rules)).
Also added in this PR is `commitlint` to ensure commit messages follow the proper format, since it's necessary for `semantic-release` to work properly. Here's an example of `commitlint` in action:
> Add semantic-release integration

- .travis.yml
Currently, we run tests in Travis on Node 4, 6, and `stable`, which is the latest stable version.
This PR uses Node 8 instead of `stable` for two purposes:
- It's the recommended stable version [Node's website](https://nodejs.org/en/).
- We use `travis-deploy-once` in conjunction with `semantic-release`, and `travis-deploy-once` looks at version numbers to determine the newest. Therefore, it was previously choosing to release on Node 6. With this new configuration, releases will happen on Node 8 builds.
> Use Node 8 instead of stable in Travis

- authorization/v1.ts
- test/unit/test.authorization.v1.js
- test/unit/test.iam_token_manager.js
The `Authorization` service is used in the Javascript SDK to fetch Watson tokens to use as query parameters. Now that Watson tokens are being deprecated, this SDK should be able to return IAM tokens when instantiated with IAM-type credentials like the other services. This PR implements this change, along with a test.
This essentially wraps the token manager in yet another SDK. This shouldn't get much usage, but it makes transitioning the Javascript SDK to RC much easier, so it is worth including.
> feat: auth service now supports returning IAM tokens

- .travis.yml
The Travis build was failing before because it was trying to run the deployment section on every Node version we use in Travis, which meant running `npx` on Node 4, which is unsupported.
This PR makes a quick fix to explicitly run the deployment script only on Node 8.
> Only run deployment section on Node 8

- README.md
- lib/recognize-stream.ts
Added the deprecation message in the README, and within the block that checks if the user passed `token` or `watson-token` as a query param.
> docs: add deprecation message for using watson-tokens

- lib/recognize-stream.ts
- speech-to-text/v1.ts
This PR will add the acoustic_customization_id at the RecognizeStream
**Can't run the tests:**
```
> nyc mocha test/unit/ test/integration/ && nyc report --reporter=html
module.js:549
throw err;
^
Error: Cannot find module '../../index'
```
> Support acoustic customization

- test/integration/test.speech_to_text.js
The tests were failing because the customization tests relied on each other (`deleteWord` needed `addWord` to add words to delete). Since the customization tests take the longest, I decided to tag the whole block with `@slow`. 
I also tagged the websockets tests from environment credentials as I noticed they were taking up to 8 seconds each.
The tests should pass now.
> test: skip all customization tests, as they rely on each other

- README.md
- examples/speech_to_text.v1.js
- examples/speech_to_text_microphone_input/transcribe-mic-to-console.js
- examples/speech_to_text_microphone_input/transcribe-mic-to-file.js
- lib/recognize-stream.ts
- speech-to-text/v1.ts
- test/integration/test.speech_to_text.js
- test/unit/test.speech_to_text.v1.js
Renamed `createRecognizeStream` to `recognizeUsingWebSocket` to achieve consistency with the other SDKs. `createRecognizeStream` wrapper method left for compatibility.
Examples, tests, and documentation updated.
> Add method recognizeUsingWebSocket

- .releaserc
- CHANGELOG.md
Moving back to using `CHANGELOG.md` for the changelog, now that we can use `semantic-release` to automate continuously updating it and bundling that change with releases.
- Moved the existing changelog back to the file so that the history is there
- Added configuration to the `.releaserc` for updating and committing the changelog
I think I modified the `.releaserc` correctly but @lpatino10 if you could double check me on that, I would appreciate it!
> Use changelog

- examples/browserify/package-lock.json
- examples/browserify/package.json
- examples/conversation_tone_analyzer_integration/package-lock.json
- examples/conversation_tone_analyzer_integration/package.json
- examples/speech_to_text_microphone_input/package.json
- examples/speech_to_text_microphone_input/transcribe-mic-to-console.js
- examples/webpack/package-lock.json
- examples/webpack/package.json
- lib/recognize-stream.ts
During a support session, I discovered that the example for using STT to stream from the microphone to the console was broken. This was due to the `interim_results` parameter not being passed in as `true`, as it defaults to `false`.
I updated the example to use the correct parameter and changed the JSDocs for `RecognizeStream` because they incorrectly listed the default value for `interim_results` as `true`.
ref:
From the [Speech to Text](https://www.ibm.com/watson/developercloud/speech-to-text/api/v1/curl.html?curl#websocket_methods) docs:
> **interim_results**
If `true`, the service returns interim results as a stream of JSON `SpeechRecognitionResults` objects. If `false`, the service returns a single `SpeechRecognitionResults` object with final results only.
Default: `false`
cc …
> Update mic stream example

- test/integration/test.discovery.js
Not sure how this got left in, but I was previously saving this `document_id` for the `createEvent` test before I decided to make a new document. This PR removes that old code.
> chore: remove artifacts of previous work

- examples/browserify/package-lock.json
- examples/browserify/package.json
- examples/conversation_tone_analyzer_integration/package.json
- examples/package-lock.json
- examples/package.json
- examples/speech_to_text_microphone_input/package-lock.json
- examples/speech_to_text_microphone_input/package.json
- examples/webpack/package-lock.json
- examples/webpack/package.json
I noticed that the examples were all using version 2.42 of the SDK when the dependency was
```
"watson-developer-cloud": "*",
```
To keep the examples up to date with SDK development, I updated the dependency to be
```
"watson-developer-cloud": "latest",
```
> chore: examples use latest version of `watson-developer-cloud`

- discovery/v1-generated.ts
- lib/helper.ts
- test/integration/test.discovery.js
I added logic in the generator to include a filename parameter in methods with file parameters. If `x-include-filename` is `true` in the API doc, a warning statement will be printed asking the user for a filename. In the next major release, the warning will be removed and the filename parameter will be required.
I changed the "filename builder" in `lib/helper.ts` to use a `filename` parameter if it is passed in. I gave this higher priority than any of the methods of interpreting the filename from the file itself - let me know if you think that should be changed.
> fix: add an optional filename parameter for methods accepting a file

- commitlint.config.js
- test/integration/test.discovery.js
- test/integration/test.speech_to_text.js
- test/unit/test.visual_recognition.v3.js
The events in between the `start_time` and `end_time` designated in the integration tests must have been deleted and this was causing the tests to fail.
This PR also includes the chore edits to resolve linting errors flagged by Codacy.
> Fix tests and codacy issues

- assistant/v1.ts
- conversation/v1-generated.ts
- discovery/v1-generated.ts
- language-translator/v2-generated.ts
- language-translator/v3.ts
- lib/base_service.ts
- natural-language-classifier/v1-generated.ts
- natural-language-understanding/v1-generated.ts
- speech-to-text/v1-generated.ts
- test/unit/test.base_service.js
- visual-recognition/v3-generated.ts
Regenerate with latest changes to API definitions and Watson Swagger Codegen.
> Regenerate sdk release 7

- README.md
- lib/base_service.ts
- lib/recognize-stream.ts
- speech-to-text/v1.ts
- test/unit/test.base_service.js
The SSL disabling option I added for the last release did not cover the WebSocket connection (thanks @lpatino10 for the catch).
This PR resolves this by taking the user option, passing it to the `RecognizeStream` class, and using it to configure the connection. It does this by creating a `tlsOptions` parameter, which gets passed into Node's native `http` library [according to the `websocket` docs](https://github.com/theturtle32/WebSocket-Node/blob/master/docs/WebSocketClient.md#client-config-options).
@lpatino10 confirmed this fix works with ICP.
cc @germanattanasio
> Disable ssl for websocket

- .travis.yml
- package-lock.json
- package.json
As Node 4 has officially reached EOL, we should not support it in the next major version of the SDK.
This PR bumps the minimum supported engine to v6 in the `package.json` file and removes the Node 4 tests from being run on Travis.
I couldn't think of any code that was an artifact of Node 4 restrictions so I didn't change any code. If anyone else knows of something in the code we should change, let me know.
> Drop node 4 support

- README.md
- examples/visual_recognition.v3.js
A user pointed out that the Visual Recognition example should not use `api_key` now that all of the instances of the service using the old API key authentication have been ended.
This updates the README and the example to prevent further confusion for users.
In the next major version, the code for handling the `api_key` parameter will be removed (unless you think we should do that now).
cc @SirSpidey
> Update vis rec examples

- conversation/v1.ts
- discovery/v1-generated.ts
- language-translator/v2.ts
- personality-insights/v3-generated.ts
- speech-to-text/v1-generated.ts
- test/unit/test.discovery.v1.js
- text-to-speech/v1-generated.ts
- tone-analyzer/v3-generated.ts
- visual-recognition/v3-generated.ts
- visual-recognition/v3.ts
- Regenerate with new changes to service
- Add deprecation messages for Conversation V1, `api_key` in VisRec, and LTv2 (there was JSDoc for this but never a console message).
> Regenerate sdk release 9

- README.md
Added the following note to the readme:
> Watson Assistant v2 API is released in beta. For details, see the ["Introducing Watson Assistant"](https://www.ibm.com/blogs/watson/2018/03/the-future-of-watson-conversation-watson-assistant/) blog post.
> update readme for assistant-v2

- .travis.yml
- lib/base_service.ts
- package-lock.json
- package.json
This PR addresses two things:
1. The Travis docs state that:
> TRAVIS_PULL_REQUEST is set to the pull request number if the current job is a pull request build, or false if it’s not.
Currently, we are checking if `TRAVIS_PULL_REQUEST` is `true` and running unit tests if so:
```
- if [ "${TRAVIS_PULL_REQUEST}" = "true" ]; then npm run test-unit; fi
```
I noticed that this hasn't been working and isn't actually running the unit tests on PR builds. I am guess this is because we are checking for `true` when it should be a number. I changed the script to use `if/else` logic to determine what to do on PR builds.
2. Regarding my PR for incorporating the new unit tests - `jest` does not run on Node v4.x (most major tools have dropped support for Node v4). Rather than use an older version of …
> build: fix travis script, stop testing node 4

- examples/text_to_speech_websocket.js
- lib/synthesize-stream.ts
- test/integration/text_to_speech.test.js
The `SynthesizeStream` class has a bug - any query parameters provided by user get appended to the URL without a proper separator (i.e. `?`). This creates an invalid URL that prevents a connection.
This PR fixes that bug and resolves #816
> Fix tts websocket bug

- assistant/v1.ts
Patching Assistant V1 with the correct placement of `disabled`.
> fix: Remove the `disabled` property from `CreateDialogNode`

- speech-to-text/v1.ts
Currently, `recognize` is hand-written and does not even call the super method. The hand-written method is outdated and buggy. The only code that differentiates it is changing the URL when a `session_id` is passed in. Session IDs are no longer supported, so this part of the code doesn't matter (although it can be added back in if there's still a chance users are taking advantage of this feature).
It also converts the `keywords` array into comma-separated strings, but this is not required. The service accepts an array.
It's buggy because it only allows `audio` to be type `Stream`, even though we document (and the service supports) other types, like `Buffer`. 
Otherwise, the generated method for `recognize` behaves exactly the same. There is a limitation that occurs for both the …
> stt: use the generated method for non-websockets recognize

- .pre-commit-config.yaml
- .secrets.baseline
- package.json
- test/integration/speech_to_text.test.js
Added `detect-secrets` tool as a precommit hook. Also modified the existing precommit hook to omit running the unit tests, as this step took way too long (> 5 seconds). That precommit hook should serve primarily to lint the code for style.
> Add detect secrets

- lib/recognize-stream.ts
The method for retrieving a transaction ID in `RecognizeStream` is using an outdated event `connect` that causes it to fail. This needs to be updated to `open` in order to work.
Additionally, `grammar_name` and `redaction` are not meant to be query parameters for the WebSocket method. They are in the HTTP method, so I put them there in the last release. A bug was reported in another SDK that these do not work as query params, so I am updating this SDK before a user runs into the issue.
> fix: fix `getTransactionId` method for the `RecognizeStream` class

- assistant/v1.ts
- compare-comply/v1.ts
- discovery/v1-generated.ts
- lib/common.ts
- speech-to-text/v1-generated.ts
- test/integration/discovery.test.js
- test/unit/assistant.v1.test.js
- test/unit/discovery.v1.test.js
- test/unit/requestWrapper.test.js
- test/unit/speech-to-text.v1.test.js
- visual-recognition/v3-generated.ts
Regenerate the SDKs. Adds new properties for CnC models, new `force` parameter for STT, new `getStopwordListStatus` method for Discovery (with tests).
Also fixes a typo @AnthonyOliveri pointed out in the Analytics header.
> Regenerate sdk release 2 2019

- README.md
- lib/base_service.ts
- test/unit/baseService.test.js
This PR adds a new method to the base service class to set the service URL after the service was initialized. All the other SDKs provide a method or means to do this, so this is just bringing the Node SDK up to par with the other SDKs.
> chore: Add setServiceUrl method to base service class

- .travis.yml
- package-lock.json
- package.json
The package `dotenv` contains code in v6 that is incompatible with Node v4.x. To maintain compatibility, I downgraded `dotenv` to v2. I confirmed that this allows the code to run with Node v4.
I also added a tool that will check new dependencies for incompatibility with supported Node versions.
Todo:
> fix: use dotenv v5 to maintain node 4.x compatibility

- UPGRADE-4.0.md
- discovery/v1-generated.ts
For certain parameters, the service changed to only allow strings instead of arrays. The SDK was supporting arrays, so to maintain compatibility we have been making hand-edits to the generated code. This PR removes those edits and allows the code to match the service.
> refactor: in `query` and `federatedQuery`, only accept string values

- UPGRADE-4.0.md
- assistant/v1.ts
- package-lock.json
- test/integration/assistant.v1.test.js
- test/unit/assistant.v1.test.js
Changing parameter `export` to `_export` in Assistant v1 since "export" is a reserved word in JS. 
Updated tests and documentation. I generated this for accuracy, a couple comments got updated but I ignored them since they'll change before the release anyways.
Resolves DevX issue 6226
> Escape export variable

- lib/recognize-stream.ts
- lib/synthesize-stream.ts
The WebSocket implementations for both STT `recognize` and TTS `synthesize` allow for an `access_token` parameter. The SDKs need to add this parameter to the allowable values whitelist. This fix is also needed for the JS Speech SDK to allow usage with IAM services.
> fix: make `access_token` an allowable query parameter for websockets

- compare-comply/v1.ts
- discovery/v1-generated.ts
Requiring filenames now happens when two conditions are met:
1) `x-include-filename` is set to `true` in the API definition
2) The file parameter that the filename is associated with is required
This is how the new (OAS3) generator handles things out of the box and it seems appropriate. I've gone in and changed the two methods these conditions are met for.
If anyone thinks we should be taking a different approach, let me know.
cc @mkistler
> refactor: require filenames where applicable

- iam-token-manager/v1.ts
- test/unit/iam-token-manager.test.js
- tsconfig.json
Removing the Token Manager as a module was an unintended breaking change. This PR fixes that by adding it back as a module of the SDK, just importing the code from the core.
> fix: expose token manager from core code as a module

- iam-token-manager/v1.ts
- package-lock.json
- package.json
This PR bumps the version of `ibm-cloud-sdk-core` which adds functionality for users to authenticate with ICP using `iam_apikey`. This is should be the final update for v3 of this SDK, aside from bug fixes.
> fix: allow users to use `iam_apikey` when authenticating for icp

- package-lock.json
- package.json
Updates the [vcap_services](https://github.com/germanattanasio/vcap-services) to the newest version.
> chore: update vcap_services dependency

- package-lock.json
- package.json
- added `commitlint` rules. Resolves #867 
- updated some vulnerable dependencies per `npm audit` review.
> fix: added commitlint rules

- package-lock.json
- package.json
This updates file-type to its newest version (10.11.0) while also dropping the now deprecated @types/file-type (as it was folded into file-type in version 10.9.0) so that `npm install` doesn't complain about the deprecated package.
> chore: update file-type dependency and drop deprecated @types/file-type

- test/integration/assistant.v2.test.js
- test/integration/compare_comply.test.js
This fixes running the test suite locally when you have not created a test/resources/auth.js script as these two tests (integration/assistant.v2.test.js and integration/compare_comply.test.js) both relied on undefined elements of `auth` before we hit the describe skip blocks.
> test: fix skipping two integration tests without auth.js

- .travis.yml
This fixes running the test suite on Travis-CI for forks as the first two arguments were throwing errors which in the case of the second line, caused the build to be left in the wrong folder causing the rest of the build to crash.
Examples:
Bad: https://travis-ci.com/MasterOdin/node-sdk/builds/110188118
Good: https://travis-ci.com/MasterOdin/node-sdk/builds/110188457
> test: fix running tests on non-ibm travis-ci

- README.md
This is a doc-only update to the README to change all the examples to use IAM rather than basic auth and promises rather than callback-style response handling. It also replaces the old "bluemix" domains with "cloud.ibm.com".
> docs: update README to use IAM and promises in all examples

- .gitignore
- .travis.yml
- package.json
- scripts/report_integration_test.js
- test/integration/assistant.v1.test.js
- test/integration/assistant.v2.test.js
- test/integration/compare_comply.test.js
- test/integration/discovery.test.js
- test/integration/language_translator.v3.test.js
- test/integration/natural_language_classifier.test.js
- test/integration/personality_insights.v3.test.js
- test/integration/speech_to_text.test.js
- test/integration/text_to_speech.test.js
- test/integration/tone_analyzer.test.js
- test/integration/visual_recognition.test.js
- test/resources/service_error_util.js
When service returns a 500+ status code, it is an indication that the error is on the service side instead of user side. In such scenario, we document the failure and do not fail the build.
> build: do not fail integration test when service is flaky

- visual-recognition/v3.ts
This fix address a problem with `updateClassifier` related to the `UpdateClassifierParams` interface. The interface was specifying `Map` as the type for `positive_examples`, but it should have been a `Record` based on reading [the code](https://github.com/watson-developer-cloud/node-sdk/blob/2ed11004bb22b3d3e6d2fa8a449f0b290722b057/visual-recognition/v3.ts#L531) since a call to `Object.keys` on a `Map` returns empty array instead of a set of keys.
Using a `Map` causes update calls to to fail with a 500 status since the zip data is not sent in the request body. 
I didn't update tests since this is purely a types fix and I didn't spot any specific test to change.
Running tests fails for me with `Jest encountered an unexpected problem`. Here is sample output:
```
SyntaxError: …
```
> fix: use Record instead of Map type for classifier update

- lib/recognize-stream.ts
This fixes a bug in `lib/recognize-stream.ts` where on Node 12 using it would throw the following error:
```
TypeError: Cannot set property readableObjectMode of #<Readable> which has only a getter
at new RecognizeStream (./node_modules/ibm-watson/lib/recognize-stream.js:126:38)
```
This is because Node 12.3 added a [readableObjectMode](https://nodejs.org/docs/latest-v12.x/api/stream.html#stream_readable_readableobjectmode) getter to the Readable stream prototype. This patch changes it such that it now explicitly sets the `readableObjectMode` option before passing it to the Duplex constructor (which in turn gets passed to the Readable constructor).
It should be noted that on Node 10 and below (which is how it currently works), `this.readableObjectMode` can be `true / undefined` while on …
> fix: only set readableObjectMode in recognize-stream if not present

- speech-to-text/v1.ts
Fills out typing information on some of the functions that had implicit `any` on their parameters/return. There's still some missing, principally for types that need to be defined in the v1.ts file. For those types, should they be defined as an interface/type under a `SpeechToTextV1` namespace in `v1.ts` or is there some other preferred method? https://github.com/watson-developer-cloud/node-sdk/issues/637#issuecomment-373130130 seems to indicate that you folks were going to move away from namespaces, but not sure the status of that.
The three imports removed were not used at all in the file. There's still two defined conts (`protocols` and `PARAMS_ALLOWED`) and function (`formatChunk`) that still exist.
Related to #764.
> refactor: fill out more typing on speech-to-text/v1

- .travis.yml
Pushes to master on forks will fail on Node 8 as it runs the deploy section as it attempts to make a push to this repo. This PR modifies Travis-CI to only run the `deploy` section only if the build is running on watson-developer-cloud/node-sdk.
example: https://travis-ci.com/MasterOdin/node-sdk/jobs/215648162
> ci: only run deploy on watson-developer-cloud/node-sdk repo

- authorization/v1.ts
Adds typing information to `authorization/v1`. No functionality in the class was changed.
Some notes (possible changes I think for v5):
* Had to disable a tslint rule for the existing class variable `target_url`. Didn't want to change it to pass tslint and break backwards compatibility.
* Should the callback be mandatory for getToken? Currently, it's possible to do `auth.getToken({url: auth.target_url});` which will cause the following error to be shown (if using the `apikey` method at least):
```
(node:30952) UnhandledPromiseRejectionWarning: TypeError: cb is not a function
at /Users/mpeveler/Work/Github/node-sdk/node_modules/ibm-cloud-sdk-core/auth/jwt-token-manager-v1.js:77:24
at /Users/mpeveler/Work/Github/node-sdk/node_modules/ibm-cloud-sdk-core/lib/requestwrapper.js:206:13
at …
```
> refactor: add typing to authorization/v1

- lib/recognize-stream.ts
The hand-written WebSocket method for Recognize has gotten out of date with the service. This prevents users from being able to pass in all the parameters that should be supported. This PR adds all currently supported parameters based on the API Documentation for STT.
> fix(speech-to-text): support all allowed parameters in WebSocket method

- lib/recognize-stream.ts
- lib/synthesize-stream.ts
- test/unit/speech-helpers.test.js
It occurred to me the other day that, in the websocket methods, there is no need to wrap the token request logic in an "is authenticated" style boolean variable. If the same Stream class is closed and used to open another connection, the token could not be refreshed. Also, if the token is stored and not expired, there is no performance hit from the logic because the token manager will give back the stored token.
This is a small change but I felt like it was worth it to make.
> fix: refresh iam tokens in websocket methods

- package.json
It takes _way_ too long, ~90 seconds, to run `npm install`
> build: remove prepare step that runs synk

- .travis.yml
- README.md
- package-lock.json
- package.json
bumping the core version will include the deprecation notice from the base service in the code
also added the notice to the "announcement" section of the readme
> docs: add deprecation notice for node versions 6 and 8

- authorization/v1.ts
Though typing authorization/V1 were updated in https://github.com/watson-developer-cloud/node-sdk/pull/910, definitions for `iam_apikey` and `ibm_url` options are missing.
http://watson-developer-cloud.github.io/node-sdk/master/#authorization
> fix: AuthorizationV1.Options requires type definitions for iam_apikey and ibm_url

- lib/recognize-stream.ts
- lib/synthesize-stream.ts
- test/unit/speech-helpers.test.js
This resolves both #849 and #902. I'm sad to say that this is all that was causing the issue - putting the objects into `extend()` in the wrong order, causing the refreshed tokens to be overwritten by the old ones. Once the old token expired, no further new connections could be made.
Test case added to verify the fix.
> fix: properly store refreshed tokens in websocket libraries

- assistant/v1.ts
- compare-comply/v1.ts
- discovery/v1.ts
- language-translator/v3.ts
- natural-language-classifier/v1.ts
- natural-language-understanding/v1.ts
- speech-to-text/v1-generated.ts
- test/unit/assistant.v1.test.js
- test/unit/compare-comply.v1.test.js
- test/unit/discovery.v1.test.js
- test/unit/language-translator.v3.test.js
- test/unit/natural-language-classifier.v1.test.js
- test/unit/natural-language-understanding.v1.test.js
- test/unit/speech-to-text.v1.test.js
- test/unit/text-to-speech.v1.test.js
- test/unit/visual-recognition.v3.test.js
- text-to-speech/v1-generated.ts
- visual-recognition/v3.ts
The logic for ordering methods in the generator changed recently and I have been disabling the ordering manually for the last couple releases. This PR changes the order of the methods to be consistent with what the generator wants to generate. This is a truly horrendous diff but it only needs to happen once to get up to date. All the other SDKs did this in one of the recent releases but I've been putting it off.
Also, for some reason, the Speech to Text changes for the regular release this week didn't make it. They are pretty much only docs changes, but they are included in this PR.
I split up the changes into 2 commits so that they would be easier to review.
Commit 1. Just the STT regeneration changes
Commit 2. Just the re-ordering. No other changes whatsoever.
> Reorder operations

- assistant/v1.ts
- assistant/v2.ts
- authorization/v1.ts
- compare-comply/v1.ts
- discovery/v1.ts
- language-translator/v3.ts
- natural-language-classifier/v1.ts
- natural-language-understanding/v1.ts
- package-lock.json
- package.json
- personality-insights/v3.ts
- speech-to-text/v1-generated.ts
- text-to-speech/v1-generated.ts
- tone-analyzer/v3.ts
- visual-recognition/v3.ts
We expose the `axios` config options in the constructor but we don't allow any flexibility in the constructor options type. This will allow TypeScript users to use the request parameters like the `axios` config properties.
Waiting to merge until these changes are made in the core and in the generator.
Edit: generator changes merged in and core version updated to include the corresponding changes.
> fix: extend constructor options types to allow additional properties

- README.md
- package-lock.json
- package.json
* fix added by bumping core to 0.3.5, which includes the important changes
* this will allow users to configure all requests, which fixes a bug that prevented use of the SDK behind a corporate proxy
* documentation added for this use case in the readme
Also, removed some read docs from the readme - couldn't fine the `setServiceUrl` method anywhere in this SDK or the core.
> fix(core): share request config across all requests

- speech-to-text/v1.ts
- test/unit/speech-helpers.test.js
- text-to-speech/v1.ts
I recently noticed that the analytics headers for the WebSocket methods do not follow the new format. Making this quick change to correct them
> fix: send correct user-agent header for websocket methods

- lib/common.ts
This will hopefully be a temporary fix until we have a better solution. Should resolve #884
> fix: disable analytics headers in browser to fix cors issues

- lib/common.ts
Adds proper return type for getSdkHeaders in lib/common.ts
> refactor: add return type to getSdkHeaders

- README.md
This fixes the anchor link to the ICP section in the README.
> docs(icp link): fix anchor link to ICP sections

- package.json
- test/integration/assistant.v1.test.js
The `object.assign` package is unnecessary if using Node 4+ when the `Object.assign` method became available. It looks like other tests use `Object.assign` as well already.
> refactor: remove unneeded object.assign devDependency

- lib/recognize-stream.ts
- speech-to-text/v1.ts
This adds typing for the three functions of `./speech-to-text/v1.ts` that lacked them, as well as removes any implicit definitions of any in the file.
I decided it would be more pragmatic to make `RecognizeStream.Options` a superset of `Duplex.Options` and `SpeechToTextV1.RecognizeWebSocketParams` and not duplicate the definitions across the two files, especially given the stream is only used for that particular method in the SDK itself.
I also added the optional bit to all optional properties of `RecognizeStream.Options` as part of this.
I used `extend` a couple of times (as it was already in the project and in this file) so that I wouldn't have to make (for example) `WhenCorporaAnalyzedOptions.errorFilter` "optional" to allow it to be defined on the next line. I didn't do that with …
> refactor: add typing to all non-generated functions of speech-to-text

- package.json
`dotenv` was used back when `ibm-cloud-sdk-core` was part of this package, but since it was removed, `dotenv` is no longer directly used in any of the code except under some of the examples. It does remain in the tree though, so no change to package-lock.json:
```
ibm-watson@5.0.0-rc1 /Users/mpeveler/work/github/node-sdk
├─┬ ibm-cloud-sdk-core@1.0.0-rc1
│ └── dotenv@6.2.0
└─┬ semantic-release@15.13.24
└─┬ @semantic-release/npm@5.1.15
└─┬ npm@6.11.3
└─┬ libnpx@10.2.0
└── dotenv@5.0.1
```
> refactor: remove dotenv as direct dependency

- package-lock.json
- package.json
Updates the `@commitlint` dependencies to their latest versions, fixing another 5 vulnerability reports from running `npm install`. The big change from `7.*` to `8.*` was:
* fix: avoid excessive help text #606 (#637) The commitlint default formatter is now silent for reports without warnings or errors. Scripts relying on the success output of commitlint can restore the former output by specifying the --verbose flag.
However, this has no effect in usage with husky, and the usage string remains the same. However, given their connection, I also updated husky as well from `1.*` to `2.*` where the breaking change was that it dropped Node 6 support. The commitlint repo dropped Node 6 support on the `8.1.0` release.
There is an even newer version of husky (v3) that is available, but it adds a …
> chore: update @commitlint/cli and husky dev dependencies

- package-lock.json
- package.json
Updates typedoc to latest version, removing the final `2` npm reported vulnerabilities.
This update does include a change in behavior with how headers in the index.html file are generated, namely that it will automatically wrap a `href` tag around it and make it a link. This is from https://github.com/TypeStrong/typedoc/pull/98
An example of what this change looks like in the diff (first is new, second is old):
```
$ diff doc-0.15 doc-0.14
< 				<a href="#watson-apis-nodejs-sdk" id="watson-apis-nodejs-sdk" style="color: inherit; text-decoration: none;">
< 					<h1>Watson APIs Node.js SDK</h1>
< 				</a>
---
> 				<h1 id="watson-apis-node-js-sdk">Watson APIs Node.js SDK</h1>
```
This only affects the index page, all other generated pages are not changed, but does affect all headers that …
> chore: update typedoc to 0.15.0

- lib/synthesize-stream.ts
Fixes #956 
As discussed in the issue, the SythesizeStream is currently outputting all information, be it strings or binary data to the pipe (after converting to a Buffer). However, following the [example](https://github.com/watson-developer-cloud/node-sdk/blob/master/examples/text_to_speech_websocket.js), this will lead to a file that is invalid as it will append both the text and binary to the same file.
This PR separates out the information, and outputs the information onto their own relevant channel as documented for the different types of information strings on the documentation:
* https://cloud.ibm.com/docs/services/text-to-speech?topic=text-to-speech-usingWebSocket
* https://cloud.ibm.com/docs/services/text-to-speech?topic=text-to-speech-timing
(the bottom of the second …
> feat: separate strings out of primary SynthesizeStream pipe

- .npmignore
Fixes #952 
Adds npmignore rules for files that are not necessary for the NPM install to work, which should slim down the size of the npm install by ~926kb.
> fix: ignore unecessary files for npm releases

- lib/recognize-stream.ts
- lib/synthesize-stream.ts
- lib/websocket-utils.ts
- package-lock.json
- package.json
Removes the `object.pick` dependency from package.json and cleans up `object.emit` and `extend` from two files that were not using it.
`lib/{recognize,synthesize}-stream.ts` stopped using `object.pick` in aee5a816e50e1f6b36fac2124a44b1798879f66d
`lib/websocket-util.ts` stopped using `extend` in 96901cfb86e178d770b72d2cf0b1dde5750cfc4d
`object.emit` is not even in package.json, but since it wasn't referenced, `tsc` was just auto-removing it when building the file so that was not causing any sort of build errors (I think).
> chore: remove unused object.pick and objec.emit dependencies

- lib/recognize-stream.ts
- lib/synthesize-stream.ts
- speech-to-text/v1.ts
- text-to-speech/v1.ts
Adds typings for `text-to-speech/v1.ts`, using a similar approach as the `speech-to-text/v1.ts` typings in that the Stream Options are split across the two files as appropriate.
> refactor: add typings for tts/v1

- package-lock.json
Updates handlebars in the package-lock tree (used as a sub-dependency by three packages), getting rid of 3 new NPM audit vulnerabilities related to a [prototype pollution issue](https://www.npmjs.com/advisories/1164). All of the affected dependencies are devDependencies (jest, semantic-release through three layers of sub-dependencies, and typdoc).
> chore: update handlebars in package-lock tree

- package-lock.json
- package.json
The first of a couple of `@types` adding PRs.
Adds `@types/isstream` to give type hinting for the `isstreams` npm package. It's only used in one place and correctly, so no code changes required.
Removes the unrelated/used `@types/is-stream` package.
> chore: replace @types/is-stream with proper @types/isstream  package

- package-lock.json
- package.json
- speech-to-text/v1.ts
This adds `@types/async` and fixes an incompatible type that was being passed to it (it requires a concrete usage of `interval` and `times`, which is provided via the use of `extend` where the CheckParams interface is used.
> refactor(typing): add @types/async and fix typing for its usage

- package-lock.json
- package.json
Moves `snyk` to be a `devDependency` as its only usage is in `npm run snyk-protect`.
> build: move snyk to be dev dependency

- examples/webpack/README.md
- examples/webpack/webpack.config.js
This change accompanies changes in the [Node-SDK-Core](https://github.com/IBM/node-sdk-core) which eliminate the requirement of adding special configuration (polyfills) in bundlers like webpack.  The workarounds are still required for versions <5.0.0 of the SDK.
> chore: update documentation for webpack

- README.md
- text-to-speech/v1.ts
Starting with v4.0.0, the data from the HTTP `synthesize` method has been deserialized into a Stream rather than a Buffer. This introduced a problem with the `repairWavHeader` method, which takes in a Buffer and returns it synchronously.
This PR adds another method, `repairWavHeaderStream`. It takes in the Stream returned from the service and asynchronously reads it into memory and repairs it. The method returns a Promise that resolves with the repaired data.
I've updated the documentation, which was out of date and incorrect, to instruct users on how to use the new method.
Resolves #911
> feat(text-to-speech): add method to repair wav header for a stream

- package-lock.json
- visual-recognition/v3.ts
Adds a dummy filename parameter to `createClassifier` positive examples so as to not break usage with the service when using Buffers. Since we can't read the filename from a Buffer, none gets sent. The service wants a filename, so behavior is messed up. The service doesn't actually ever use the filename, so a dummy here should be fine.
If this fixes behavior for #984, I will make this patch to v5 as well.
> fix(visual-recognition-v3): add dummy filename parameter

- lib/recognize-stream.ts
- lib/synthesize-stream.ts
- package-lock.json
- package.json
Adds missing `@types/websocket` package and removes unused `@types/csv-stringify` to complete typing information for all external packages. Had to make one slight code in `lib/recognize-stream.ts` to `[header: string]: string | string[]` defined and have to tell the compiler to narrow that to just `string` for the header in question.
I also removed a totally unused type def on the SynthesizeStream interface (`_readableState`) while I was looking at the files.
> chore: add missing @types/websocket

- discovery/v2.ts
> fix: add hand-edits to discovery v2 aggregation models

- .github/CODE_OF_CONDUCT.md
Adding code of conduct that matches other Watson SDKs
> docs: add a code of conduct

- README.md
First example in the README is missing a comma.
> docs: fix typo in first example in readme

- package-lock.json
- package.json
Upgrades the core version, which resolves #993
> fix: upgrade core version to 1.3.1

- natural-language-understanding/v1.ts
This pull request restores a field that was inadvertently removed in the last regeneration cycle.
> Restore model field in CategoriesOptions

- README.md
This PR adds documentation explaining that authenticators that makes network requests also need the proxy configured
> docs: update proxy docs to include iam auth usage

- CHANGELOG.md
- README.md
- assistant/v1.ts
- examples/personality_insights.v3.js
This pull request updates outdated links in documentation. Current redirects for these links will stop in May. This change has been made in the API definition.
> Update outdated links

- README.md
I've noticed that links "Getting started" links from the README now redirect:
For example, 
https://cloud.ibm.com/docs/services/natural-language-classifier/getting-started.html
->
https://cloud.ibm.com/docs/services/natural-language-classifier?topic=natural-language-classifier-natural-language-classifier
Since the new link is a bit ugly (duplicates "natural-language-classifier") I opted to keep the old format.
> docs: fix README typo and add link to NLU

- test/integration/language-translator.v3.test.js
- test/integration/visual-recognition.v4.test.js
We we're using the wrong model type for the glossary. I don't know why this only started happening recently
> fixes LTv3 createModel test that was failing

- package-lock.json
- package.json
Updates the core version to include a bug fix. This bug caused `disableSslVerification` to be ignored when users provided a custom https agent (which they would do if using a proxy, for example).
Code for the fix is here - https://github.com/IBM/node-sdk-core/pull/104
This also fixes a bug that was preventing query parameters to be constructed properly.
Code for that is here - https://github.com/IBM/node-sdk-core/pull/106
> fix: support `disableSslVerification` when user provides https agent

- README.md
We deprecated `url` and transitioned to `serviceUrl` a while ago. `url` is still a valid option, but we should use the proper parameter name in the README and documentation.
> docs: use `serviceUrl` instead of `url` in README

- lib/recognize-stream.ts
- lib/synthesize-stream.ts
- lib/websocket-utils.ts
This method was present on the RecognizeStream and was mistakenly left off of the SynthesizeStream when it was developed. This PR fixes that mistake.
Rather than duplicate the method between the Stream classes, I moved the core functionality to a utility function that each Stream relies on. No code has actually changed; it works exactly the same.
> fix: add `getTransactionId` method to the SynthesizeStream

- lib/recognize-stream.ts
- lib/synthesize-stream.ts
- speech-to-text/v1.ts
- test/unit/speech-helpers.test.js
- text-to-speech/v1.ts
The Websocket methods `recognizeUsingWebsocket` (STT) and `synthesizeUsingWebsocket` (TTS) were not using the `serviceUrl` parameter defined by the core. They were only looking for `url`.
The `serviceUrl` parameter is the correct one, `url` is deprecated (but still supported). In the core, `serviceUrl` and `url` are both mapped to `baseOptions.serviceUrl`, so we only need to look at that single parameter and both are supported. This is a compatible change. I updated the test to make sure the user can provide both `serviceUrl` and `url`.
Resolves #1059
> fix: stop ignoring serviceUrl for Websocket methods

- test/integration/visual-recognition.v4.test.js
The `listCollections` vis rec v4 test takes longer than current timeout period. This was increased to 30 seconds to ensure travis tests pass
> chore(vis-rec): add increased timeout for listCollections test

- README.md
This PR adds a special note for using the credentials file authentication option with assistant. Legacy issues prevent this from being a quick fix but the README should at least address this issue.
> docs: add special note regarding use of credentials file with assistant

- README.md
- assistant/v1.ts
- assistant/v2.ts
- authorization/v1.ts
- compare-comply/v1.ts
- discovery/v1.ts
- discovery/v2.ts
- examples/browserify/.env.example
- examples/webpack/.env.example
- language-translator/v3.ts
- lib/recognize-stream.ts
- lib/synthesize-stream.ts
- natural-language-classifier/v1.ts
- natural-language-understanding/v1.ts
- personality-insights/v3.ts
- speech-to-text/v1-generated.ts
- test/resources/visual_recognition.prepop/classify.sh
- text-to-speech/v1-generated.ts
- tone-analyzer/v3.ts
- visual-recognition/v3.ts
- visual-recognition/v4.ts
watsonplatform.net urls will cease to function starting 12 Feb 2021. This pull request updates gateway urls to the onecloud equivalents.
> Update gateway urls [skip ci]

- assistant/v1.ts
- assistant/v2.ts
- compare-comply/v1.ts
- discovery/v1.ts
- discovery/v2.ts
- language-translator/v3.ts
- natural-language-classifier/v1.ts
- natural-language-understanding/v1.ts
- package-lock.json
- package.json
- personality-insights/v3.ts
- speech-to-text/v1-generated.ts
- test/unit/assistant.v1.test.js
- test/unit/assistant.v2.test.js
- test/unit/compare-comply.v1.test.js
- test/unit/discovery.v1.test.js
- test/unit/discovery.v2.test.js
- test/unit/language-translator.v3.test.js
- test/unit/natural-language-classifier.v1.test.js
- test/unit/natural-language-understanding.v1.test.js
- test/unit/personality-insights.v3.test.js
- test/unit/speech-to-text.v1.test.js
- test/unit/text-to-speech.v1.test.js
- test/unit/tone-analyzer.v3.test.js
- test/unit/visual-recognition.v3.test.js
- test/unit/visual-recognition.v4.test.js
- text-to-speech/v1-generated.ts
- tone-analyzer/v3.ts
- visual-recognition/v3.ts
- visual-recognition/v4.ts
Generated SDK release using :
API Defs tag `sdk-2021-09-03`
Generator tag `3.38.0`
Discovery V1 tag `sdk-2021-09-03`
* `alt_text` property added to Image response type
​
* `session_start_time` and `state`  properties added to `MessageContextGlobalSystem` model
* `alt_text` property added to Image response type
* `location` property of `RuntimeEntity` model changed from required to optional
​
* Enum update for  `CreateProjectConstants`
​
* Fix for `listClassificationsModels` through return type change and removal of unnecessary model
​
* More languages supported for next generation models
​
* New voice models added
​
* No changes
> Hsaylor 9718 rc

- speech-to-text/v1-generated.ts
Commit https://github.com/watson-developer-cloud/node-sdk/commit/84bb18da2a4431c4f59cd95f0e05c8d61cd7ab85 rolled back PR https://github.com/watson-developer-cloud/node-sdk/pull/1085, I believe this was unintentional.
I have verified that the response type is still `[string, number, number]`, which reflects the current TSDoc too.
This change re-applies the fix created by @apaparazzi0329.
> fix(stt): timestamps type to properly reflect response model

- README.md
Noticed a couple of dead links in the README doc. One is a typo
(AUTHENTICATION.md should be Authentication.md) so I fixed that.
The other pointed at a doc on VCAP_SERVICES that doesn't exist
any more, so I changed it for the only description I could find
for VCAP_SERVICES on the public cloud docs site.
Signed-off-by: Dale Lane <dale.lane@uk.ibm.com>
> docs: fix dead links in README

- assistant/v2.ts
- test/unit/assistant.v2.test.js
This commit adds a required environmentId param to the deleteSession function. It also adds the `environments` path parameter to the /message api calls.
> fix(wa-v2): add environmentId param to more functions
