README.md

Documentation for authorization API.
Also, I need to return an error object in the token callback to be consistent with the other services.  I'll make a separate PR for this.

Authorization README addition

---

README.md
examples/speech_to_text.v1.js
examples/text_to_speech.v1.js

Update STT and TTS README and examples

---

package.json
services/concept_insights/v2.js
services/personality_insights/v2.js
services/tone_analyzer/v1.js
test/test.concept_insights.v2.js
test/test.personality_insights.v2.js

The test covers most of the API. 
On a side I have written a test that uses 100% of the api with out internal installation and all of them behaved as expected.

Added support for Concept Insights v2

---

examples/search_lifecycle.v1.js
examples/search_solr.v1.js
package.json
services/search/v1.js
test/test.search.v1.js

This adds the ability to create Solr collections.
For searching and indexing, integration with solr-node-client is used.
https://github.com/lbdremy/solr-node-client

Add Solr search and indexing capabilities.

---

examples/language_translation.v2.js
examples/resources/glossary.tmx

Merge the latest changes from dev into master

merge dev into master

---

services/speech_to_text/v1.js

fixed typo in speech to text

---

services/natural_language_classifier/v1.js
test/resources/training_data.csv
test/resources/training_data.json
test/test.natural_language_classifier.v1.js

Updating natural_language_classifier service to accept CSV trainingata. Updating API endpoint to use the new standard NLC service. Adding tests for training a classifier with JSON and CSV training data. Fixes #61

Pull request for issue #61

---

examples/search_lifecycle.v1.js
examples/search_solr.v1.js
lib/alchemy_endpoints.json
lib/index.js
services/alchemy_language/v1.js
services/alchemy_vision/v1.js
services/concept_insights/v2.js
services/personality_insights/v2.js
services/search/v1.js
services/speech_to_text/v1.js
test/test.authorization.v1.js
test/test.concept_insights.v2.js
test/test.speech_to_text.v1.js
test/test.text_to_speech.v1.js
test/test.tone_analyzer.v1.js

I did a code review and found some unused variables.

Code review

---

services/alchemy_language/v1.js
services/alchemy_vision/v1.js
services/concept_expansion/v1.js
services/question_and_answer/v1.js

Changed a few function expressions to function declaration to adhere to the formatting guide and to improve stack trace.

function expressions to function declarations

---

examples/retrieve_and_rank_lifecycle.v1.js
examples/retrieve_and_rank_solr.v1.js
lib/index.js
services/retrieve_and_rank/v1.js
test/test.retrieve_and_rank.v1.js

Leaves existing Search client for legacy users

Rename Search client to Retrieve and Rank

---

.jshintignore
.jshintrc
README.md
examples/concept_insights.v2.js
examples/natural_language_classifier.v1.js
lib/alchemy_endpoints.json
lib/helper.js
lib/index.js
package.json
services/alchemy_language/v1.js
services/alchemy_vision/v1.js
services/natural_language_classifier/v1.js
services/speech_to_text/v1.js
test/test.dialog.v1.js
test/test.natural_language_classifier.v1.js
test/test.search.v1.js
test/test.speech_to_text.v1.js

Merging the latest changes from `dev`. 
* @radleymith	change function declarations to function expressions	ddcdb4d
* @radleymith	removed an extra whitespace	 9427a99
* @nfriedly	making jshint automatically run with tests and ensuring that all cod… 58552a1
* @nfriedly	making use_vcap_services option behave as expected	 30630e7
* @nfriedly	simplifying jshint setup	 ff1fe11
* @germanattanasio	Add the cookie_session as SESSIONID to getRecognizeStatus() #86	 f4d0fa2
* @germanattanasio	fixed #85	 6833525
* @germanattanasio	added classifier_id and fallback to classifier to fix #85	 e8d9ddf
* @germanattanasio	fixed #79 Natural language classifier uses beta url	 ec97722

merge changes from dev 

---

services/tradeoff_analytics/v1.js
test/resources/ta_events.js
test/test.tradeoff_analytics.v1.js

OK, @germanattanasio, I've added tests, worked in dev, aligned with the holy coding guidelines, the whole nine yards...
Please accept the pull request so we can get this over with...

Support analytics (metadata and events) in the Tradeoff Analytics proxy

---

examples/retrieve_and_rank_lifecycle.v1.js
examples/retrieve_and_rank_solr.v1.js
services/retrieve_and_rank/v1.js
test/test.retrieve_and_rank.v1.js

This also updates the service urls in the examples.

Remove deprecated delete all API for Retrieve and Rank

---

examples/visual_recognition.v1-beta.js
examples/visual_recognition.v2-beta.js
services/visual_recognition/v1-beta.js
services/visual_recognition/v2-beta.js

Hi @nfriedly can you review this? Can you also publish `master` to npm. I think it's `beta-3`.

Support for Visual Recognition V2

---

.gitignore
CONTRIBUTING.md
README.md
test/test.document_conversion.v1-experimental.js
test/test.integration-all-services.js

The Document Conversion Service behavior can be customized by passing in
various properties as part of the conversion request. See documentation
for more details and exact config property names.

DCS: Adds example for passing custom configs

---

.travis.yml
test/test.document_conversion.v1-experimental.js

This should fix the failed Travis builds when checking Pull Requests.
It should end up skipping the integration tests, but the unit tests
should still run.

Updates travis commands for better PRs

---

examples/personality_insights.v2.js

Hi German, 
Thanks for these fantastic Watson services. This is a tiny PR -- I just noticed that the personality_insights.vs.js file needs a var fs = require('fs')  in order for the  }).pipe(fs.createWriteStream('./output.csv'));  to run at the end. All tests are passing. 
Hope you're well, Robin

Adds var fs for personality-insights

---

README.md
examples/document_conversion.v1.js
examples/document_conversion_integration.v1.js
services/document_conversion/v1.js
test/test.document_conversion.v1.js

This commit includes the GA version of the api, tests,
and examples for the Document Conversion service (v1)

[document-conversion] Adding GA version of document conversion

---

services/tone_analyzer/v3-beta.js
test/test.tone_analyzer.v3-beta.js

Added service code to pick up query parameters and add test cases.

Allow setting optional request parameters, tones and sentences.

---

lib/alchemy_endpoints.json
package.json
services/alchemy_vision/v1.js
test/test.integration-all-services.js

[alchemy-vision] Add support for Text Detection. #213

---

examples/resources/solr_docs.json
examples/retrieve_and_rank_solr.v1.js

This example will make it clearer what the JSON format should be to interact with the Node Solr client.

Add R&R example for indexing Solr docs from a JSON file

---

services/retrieve_and_rank/v1.js

Before this would result in a 406 error preventing config download.

Add accept header for getting R&R configuration

---

services/retrieve_and_rank/v1.js
test/test.retrieve_and_rank.v1.js

Config path

---

test/test.alchemy_language.v1.js

Tests for [pull 236](https://github.com/watson-developer-cloud/node-sdk/pull/236)
Thanks for contributing to the Watson Developer Cloud!

Add tests for Alchemy endpoint selection

---

examples/alchemy_language.v1.js

Adding examples for the rest of the functions

Add examples for AlchemyLanguage

---

README.md
examples/personality_insights.v2.js
examples/resources/example.html
jsdoc/generate_index_html.sh
test/resources/sampleHtml.htm
test/resources/sampleHtml.html

Remove smarter place from urls

[ci skip] :t-shirt: remove smarter planet from urls

---

conversation/v1.js

added 'alternate_intents' parameter in body pick to allow to take it into account if client sends "alternate_intents: true" in order to receive the top 10 intents

Update v1.js with "alternate_intents" parameter

---

visual-recognition/v3.js

retrain classifier is needed for VR demo stuff.

Added retrain classifier

---

visual-recognition/v3.js

replaced http:// by https:// in the endpoint url to satisfy to the new Visual Recognition API
If there's anything else that's important and relevant to your pull
request, mention that information here.
Thanks for contributing to the Watson Developer Cloud!

Changed from HTTP to HTTPS endpoint url

---

conversation/v1.js

The version date should be 2016-07-11 for the version
date in the error message.
Fixes #306

updates version in error message

---

README.md

Just update the readme with instructions for how to use the current sdk with either service

clarify language translator vs translation

---

README.md
personality-insights/v3.js
test/integration/test.alchemy_vision.js

This PR updates the example and Js doc for Personality Insights.

Update example and jsdoc

---

language-translation/v2.js
language-translator/v2.js
lib/helper.js
lib/requestwrapper.js
retrieve-and-rank/v1.js
speech-to-text/v1.js
test/integration/test.speech_to_text.js
test/resources/speech_to_text/corpus-full.txt
test/resources/speech_to_text/corpus-short-1.txt
test/resources/speech_to_text/corpus-short-2.txt
test/unit/test.speech_to_text.v1.js
text-to-speech/v1.js

I tweaked the handling of requiredparams a bit so that you can pass the original params to requestwrapper and then it'll use that instead of trying to rebuild it for the requiredparams check.
And then I implemented all of the STT customization API + a helper to notify you when processing / training is complete. And integration tests for everything. 
I should probably do unit tests too...

STT customization support

---

README.md
discovery/v1-experimental.js
examples/discovery.v1-experimental.js
lib/requestwrapper.js
package.json
test/integration/test.alchemy_vision.js
test/integration/test.speech_to_text.js
test/integration/test.visual_recognition.js
test/unit/test.discovery_experimental.v1.js

Discovery commands of collections, environments, and query are in now.

Updated to add stubs for basic discovery commands

---

examples/conversation.v1.js

Fixes #343 and adds example for conversation.

Add example for conversation.

---

package.json

Provide a general description of the code changes in your pull
request... were there any bugs you had fixed? If so, mention them. If
these bugs have open GitHub issues, be sure to tag them here as well,
to keep the conversation linked together.
If there's anything else that's important and relevant to your pull
request, mention that information here.
Thanks for contributing to the Watson Developer Cloud!
In package.json main file point to an unexisting file `lib/index`. just update and make main point to the index file in the root directory.
Without this modification, Meteor can't get this package working correctly

Fix main file path

---

speech-to-text/v1.js

Added a function  that waits until the status of STT corpus is analyzed

Add function that waits until the status of STT corpus is analyzed

---

examples/speech_to_text.v1.js

Added an example that illustrates how to use `whenCorporaAnalyzed` in STT

Add example for STT -> whenCorporaAnalyzed

---

CHANGELOG.md
speech-to-text/v1.js
test/integration/test.speech_to_text.js

Update jsdoc for the Speech to text service.
I also added a `getCorpus()` method and removed a method that was never implemented in the API.

Update jsdocs for Speech to text

---

discovery/v1.js
test/unit/test.discovery.v1.js

These allow the creation and deletion of
environments in Discovery.

add createEnvironment and deleteEnvironment

---

examples/conversation.v1.js

conversation example with two messages

---

README.md
natural-language-understanding/v1.js
test/unit/test.natural_language_understanding.v1.js

add model endpoints to NLU, tests, new version date

---

conversation/v1.js
test/integration/test.conversation.js

Hi,
I add some params to : 
listWorkspaces
getIntents
getExamples

[Conversation] Update API with pagination and sort params

---

speech-to-text/v1.js
test/integration/test.speech_to_text.js
test/unit/test.speech_to_text.v1.js

[STT] events parameter

---

conversation/v1.js
test/integration/test.conversation.js

Hi,
I added the new API about CounterExamples : 
createCounterExample,
getCounterExample,
getCounterExamples,
deletCounterExample,
updateCounterExample
:+1:

[Conversation] Add CounterExample API

---

package.json

Update vcap-services npm package to 0.3.0 releases

Bump vcap-services package version to include new features

---

discovery/v1.js
examples/speech_to_text.v1.js
test/unit/test.discovery.v1.js

[Discovery] Add natural_language_query and passages parameters to Discovery

---

discovery/v1.js
test/unit/test.discovery.v1.js

Update collections get fields

---

conversation/v1.js
test/integration/test.conversation.js

Hi,
I update the api with the fuzzy_match parameters :)
Thanks you.
Rémy.
PS: I sign the CLA, but it doesn't seem to work :/

[Conversation] Update API

---

README.md

a simple fix in the title of a doc section

adjusting doc text

---

discovery/v1.js

Pull request for Issue #477 , tested against my own code, but I've not extended the test scripts

Added a new helper method for updateJsonDocument

---

test/unit/test.tone_analyzer.v3.js
tone-analyzer/v3.js

Add content language as a parameter to Tone Analyzer

Add content language parameter to Tone Analyzer

---

discovery/v1.js

Related: https://github.com/watson-developer-cloud/node-sdk/issues/474

Add check for params.file to be of object type

---

.gitignore
language-translator/v2.ts
natural-language-classifier/json-training-to-csv.ts
natural-language-classifier/v1.ts
package-lock.json
package.json
personality-insights/v3.ts

**Summary:**
* Removed `LanguageTranslationV2` console warning from `Language Translator` adapter.
* Refactored `Personality Insights` adapter and updated adapter to work with headers in different cases(example: `content-type` and `Content-Type`)
* Converted `json-training-to-csv` to TypeScript to suppress compilation errors.
* Added type definitions for `csv-stringify`.
* Formatted `Personality Insights` adapter with pretty.

Adapter & Typings Updates

---

package-lock.json
package.json
test/unit/test.conversation.v1.js
test/unit/test.personality_insights.v3.js

Add Conversation unit tests

---

.gitignore
lib/base_service.ts
lib/helper.ts
tsconfig.json

Export interfaces for TypeScript

Export .d.ts and .js.map source maps

---

lib/requestwrapper.ts
test/integration/test.tone_analyzer.js
test/integration/test.visual_recognition.js

Adds requested error tracking enhancement to close #574

add global transaction id to error body

---

speech-to-text/v1-generated.ts
text-to-speech/v1-generated.ts
visual-recognition/v3-generated.ts

Fix Default Service URLs

---

README.md

needs to be changed to link to correct branch
temporary until travis builds correctly and this will be automatic

Updated doc link in README

---

.eslintignore
test/unit/test.adapter.tone_analyzer.v3.js
test/unit/test.personality_insights.v3.js
test/unit/test.tone_analyzer.v3.js

1. I updated the .eslintignore file to ignore the typedoc javascript files which were causing many errors in Jenkins on linting and also causing the build to take over 2 hours to complete. 
2. I also updated prettier errors in three testing files: 
- `test.adapter.tone_analyzer.v3.js`
- `test.personality_insights.v3.js` 
- `test.tone_analyzer.v3.js`

Trisha fix jenkins

---

lib/requestwrapper.ts
test/unit/test.requestWrapper.js

The purpose of this is the upcoming openwhisk SDK, where user-agent is appending something to clarify it is from the openwhisk SDK

Changed header so user-agent is not overwritten, instead appended

---

.gitattributes
dependency-lint.yml
discovery/v1.ts

Fix dependency-lint false errors and fix newline chars in discovery/v1.ts.
Might want to view the diff with "ignore space".

Lint improvements

---

natural-language-classifier/v1-generated.ts
test/integration/test.natural_language_classifier.js
test/integration/test.visual_recognition.js
test/unit/test.adapter.natural_language_classifier.v1.js
test/unit/test.assistant.v1.js
test/unit/test.visual_recognition.v3.js
visual-recognition/v3-generated.ts

Adds support for two new endpoints and adds unit tests for both of them

feat(visual recognition & nlc): vr: new coreML endpoint nlc: new classifyCollection endpoint

---

README.md
examples/natural_language_understanding.v1.js
natural-language-understanding/v1.ts
test/unit/test.natural_language_understanding.v1.js

Add new version string VERSION_DATE_2018_04_05 for NLU

---

.travis.yml
assistant/v1.ts
package.json
test/integration/test.visual_recognition.custom_classifiers.js

Assistant v1.ts had incorrect documentation
travis build now only runs all tests in case of release, normally just runs tests that are not too slow

Fixes incorrect documentation in assistant v1.ts and fixes travis build

---

README.md

I put some docs into the `README` for IAM. I basically just followed the format @lpatino10 used in the Java SDK. Let me know what y'all think, happy to change things around.

add iam section to readme

---

README.md

Adds warning for visual recognition

---

lib/base_service.ts
test/unit/test.visual_recognition.v3.js

Adds tests for VCAP_SERVICES and environment file credentials for RC instances for VR
Fixes bug where VR was not correctly getting IAM credentials from those

Fixes bug for visual recognition RC instances

---

test/integration/test.visual_recognition.custom_classifiers.js
test/integration/test.visual_recognition.js

This is temporary until we have upgraded RC credentials for VR

test(visual recognition): skips visual recognition tests to make travis pass

---

README.md

Addresses changes requested from reviewers to make the authentication section clearer as we migrate services to IAM. Makes README more consistent with other supported SDKs.
- Update intro to authentication
- Move IAM to top of the stack of auth methods. Rename to just `IAM`
- Update getting credentials section
- Move usage section to top
- Remove examples section (covered in usage)
- Update Visual Recognition note
- Change headings to sentence case
- Add `Watson services` h2 section to correspond to existing TOC
- Update TOC
- Add existing h2 `documentation`

Update authentication section for clarity

---

README.md

Already mention the TTL of the token in the previous paragraph.

Remove token statement

---

test/unit/test.speech_to_text.v1.js

Add unit tests for `recognize()` and `createRecognizeStream()`. Also commented out a set of broken tests that were causing mocha to hang. These can be renovated later but for now should not be run. Also added some extra clarifying comments.

test: add unit tests for recognize() and createRecognizeStream()

---

package-lock.json
package.json

So `@semantic-release/github` is a default dependency, but `@semantic-release/git` is not.
`@semantic-release/git` is necessary to commit the changelog and the updated version to `package.json`.
This should be the last PR necessary to implement these changes.
cc @lpatino10  in case you plan on doing this in your SDK

build: add @semantic-release/git as a dependency

---

README.md
test/integration/test.visual_recognition.js

Fixes typo in the example for Assistant v2.

fix typo in assistant v2 example

---

assistant/v1.ts
assistant/v2.ts
discovery/v1-generated.ts
language-translator/v3.ts
natural-language-classifier/v1-generated.ts
natural-language-understanding/v1-generated.ts
personality-insights/v3-generated.ts
speech-to-text/v1-generated.ts
test/integration/test.discovery.js
test/unit/test.discovery.v1.js
text-to-speech/v1-generated.ts
tone-analyzer/v3-generated.ts

Regenerates the SDKs to match current definitions of the services. Adds new methods for Discovery, as well as tests for these methods. Also adds some new lines Phil added to the template for readability so recommending to ignore newlines/whitespace in the diff.

Regenerate sdk release 10

---

.travis.yml
package-lock.json

build: cache node_modules/ in travis build

---

discovery/v1-generated.ts
lib/recognize-stream.ts
speech-to-text/v1-generated.ts
speech-to-text/v1.ts
test/unit/speech-helpers.test.js
test/unit/speech-to-text.v1.test.js

Updating STT and Discovery parameters based on recent changes to the service

Patch stt and discovery

---

package-lock.json
package.json

Updates dependencies to resolve vulnerabilities using `npm audit fix`
Resolves #857

build: fix vulnerabilities in dependencies

---

README.md
test/integration/compare_comply.test.js

1. Add an "announcements" section to alert users about the release and the package rename
2. Add a "featured projects" section with some demos and a call for other projects
cc @lpatino10

docs changes

---

README.md
package-lock.json
package.json
test/integration/compare_comply.test.js

fix: enable axios debug

---

package-lock.json
package.json

This will prevent circular JSON errors when stringifying the detailed response

fix: don't return request object in detailed response

---

assistant/v1.ts
assistant/v2.ts
authorization/v1.ts
compare-comply/v1.ts
discovery/v1.ts
examples/assistant_tone_analyzer_integration/tone_detection.js
iam-token-manager/v1.ts
language-translator/v3.ts
lib/recognize-stream.ts
lib/synthesize-stream.ts
natural-language-classifier/v1.ts
natural-language-understanding/v1.ts
personality-insights/v3.ts
speech-to-text/v1-generated.ts
test/resources/auth.example.js
test/unit/assistant.v1.test.js
test/unit/assistant.v2.test.js
test/unit/compare-comply.v1.test.js
test/unit/discovery.v1.test.js
test/unit/language-translator.v3.test.js
test/unit/natural-language-classifier.v1.test.js
test/unit/natural-language-understanding.v1.test.js
test/unit/personality-insights.v3.test.js
test/unit/speech-to-text.v1.test.js
test/unit/text-to-speech.v1.test.js
test/unit/tone-analyzer.v3.test.js
test/unit/visual-recognition.v3.test.js
text-to-speech/v1-generated.ts
tone-analyzer/v3.ts
visual-recognition/v3.ts

Regenerate sdk release 4 2019

---

compare-comply/v1.ts
test/unit/assistant.v1.test.js
test/unit/compare-comply.v1.test.js
test/unit/discovery.v1.test.js
test/unit/language-translator.v3.test.js
test/unit/natural-language-classifier.v1.test.js
test/unit/natural-language-understanding.v1.test.js
test/unit/speech-to-text.v1.test.js
test/unit/text-to-speech.v1.test.js
test/unit/visual-recognition.v3.test.js

Regenerate CnC with new model and type fixes.
Also, fix copyrights in generated unit tests

feat(compare-comply): new model ContractCurrencies added

---

README.md

V5 readme update

---

README.md

A customer was having an issue using a custom key/certificate because they were passing in filenames rather than the parsed files. This PR adds a section to the README describing how to pass in custom certificates, etc.

docs: add section to readme about using custom certificates

---

discovery/v1.ts

confiruration -> configuration

---

test/resources/auth.example.js

The example auth file is way out of date. This updates it with the correct format and correct services.

docs: update auth example file to use correct format

---

assistant/v1.ts
assistant/v2.ts
examples/assistant_tone_analyzer_integration/tone_detection.js
lib/recognize-stream.ts
natural-language-classifier/v1.ts
natural-language-understanding/v1.ts
personality-insights/v3.ts
speech-to-text/v1-generated.ts
test/integration/visual-recognition.v4.test.js
test/unit/assistant.v1.test.js
test/unit/assistant.v2.test.js
test/unit/compare-comply.v1.test.js
test/unit/discovery.v1.test.js
test/unit/discovery.v2.test.js
test/unit/language-translator.v3.test.js
test/unit/natural-language-classifier.v1.test.js
test/unit/natural-language-understanding.v1.test.js
test/unit/personality-insights.v3.test.js
test/unit/speech-to-text.v1.test.js
test/unit/text-to-speech.v1.test.js
test/unit/tone-analyzer.v3.test.js
test/unit/visual-recognition.v3.test.js
test/unit/visual-recognition.v4.test.js
text-to-speech/v1-generated.ts
tone-analyzer/v3.ts
visual-recognition/v3.ts
visual-recognition/v4.ts

Regenerates the SDK and adds tests for new methods. Some copyrights fixes in there too.

Regen 2020 02 10

---

package-lock.json
package.json

Updates the core to v2.4.2, which fixes the intermingling of test code/dependencies with the published package.
Resolves #1047

fix: update core version to 2.4.2

---

README.md

This pull request documents how to set global transaction id

Document setting of global transaction id

---

README.md

This pull request adds message for personality insights deprecation

Add PI deprecation message

---

test/integration/assistant.v1.test.js

BREAKING CHANGE: Support for callbacks dropped
BREAKING CHANGE: Support for Node v10 dropped
BREAKING CHANGE: changes to services, see MIGRATION-V6.md

test(assistant): fix test text and add BREAKING CHANGE for sr

---

.github/workflows/build-test.yml
.github/workflows/deploy.yml
README.md

Remove dry run, update README, add node 14.x

9312 ghatasks

---

natural-language-classifier/v1.ts

add deprecation warning to NLC constructor
fix #9622

fix(nlc): add deprecation warning

---

speech-to-text/v1-generated.ts

Second PR to fix STT `word_confidence` as a follow up to #1112

fix(stt): revert change to word_confidence made by 84bb18d

---

package-lock.json
package.json
speech-to-text/v1.ts
test/integration/speech-to-text.test.js

stt: fix "waiting" methods so they no longer send invalid params

fix(deps): upgrade core version to address file-type vulnerability
